# Generated by Django 5.1.2 on 2025-05-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtabel_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('rapid_id', models.CharField(db_index=True, max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtabel_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('rapid_id', models.CharField(db_index=True, max_length=32, unique=True)),
            ],
        ),
    ]
