# Generated by Django 5.1.2 on 2025-06-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0002_reel_account_username_reel_code_reel_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapid_id', models.CharField(db_index=True, max_length=48, unique=True)),
                ('base', models.CharField(blank=True, max_length=80)),
                ('table', models.CharField(blank=True, max_length=52)),
            ],
        ),
    ]
